pmem/fio

ci/travis-install-librpma.sh
ci/travis-install-pmdk.sh
ci/travis-install.sh
engines/librpma.c

The server of librpma depends on libpmem from PMDK,
so PMDK libraries have to be installed in Travis CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/31)

rpma: install PMDK libraries in Travis CI

---

engines/librpma_gpspm.c

Fix the 'conn' argument of rpma_conn_next_event()
and add an error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/60)

rpma: fix server_open_file()

---

engines/librpma_gpspm.c

Do not require the completion of rpma_send().
If it fails, the completion will be verified
next time the server_queue() is called.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/69)

rpma: do not require the completion of rpma_send()

---

engines/librpma.c

**Note**: The issue being fixed might affect bandwidth(threads) scalability.
@grom72 @ldorau @osalyk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/72)

rpma: fix client_io_write dst offset calculation

---

examples/librpma_gpspm-server.fio

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/76)

rpma: librpma_gpspm_server has to run as long as the client needs

---

engines/librpma_gpspm.c

- without collecting completions SQ is evicted lazily which may cause overrunning the SQ
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/79)

rpma: gpspm: require and collect the rpma_send's completions

---

engines/librpma.c

May profoundly affect the results at least in two ways:
- in-situ writes vs e.g. sequential may behave differently
- having bigger workspaces allows easier making use off all available
PMem DIMMs bandwidth
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/101)

rpma: fix workspace size calculation

---

engines/librpma_gpspm.c

The first one:
```
engines/librpma_gpspm.c: In function ‘common_td_port’:
engines/librpma_gpspm.c:167:44: warning: ‘%u’ directive output may be truncated writing between 1 and 10 bytes into a region of size 9 [-Wformat-truncation=]
167 |  snprintf(port_out, PORT_STR_LEN_MAX - 1, "%u", port_new);
|                                            ^~
```
The second one:
```
engines/librpma_gpspm.c: In function ‘common_td_port’:
engines/librpma_gpspm.c:167:46: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
167 |  snprintf(port_out, PORT_STR_LEN_MAX - 1, "%u", port_new);
|                                              ^
In file included from /usr/include/stdio.h:866,
from engines/../fio.h:11,
from engines/librpma_gpspm.c:17: …
```

rpma: gpspm: fix two warnings

---

engines/librpma.c
examples/librpma-server.fio

- spawns multiple threads
- each thread creates a peer, an endpoint and a memory registration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/109)

rpma: use num_jobs instead of num_conns

---

engines/librpma.c

- each thread workspace starts from offset 0 of its registration
- no need for passing from server to client assumed workspace size
- no need for allocating an excessive amount of DRAM just to make sense of the client-assumed workspace offset
- no need for registering the whole PMEM when only its part is in use via a specific registration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/112)

rpma: each thread registers only its own workspace

---

engines/librpma.c
engines/librpma_common.h
engines/librpma_gpspm.c

**Note**: This change may affect performance because a piece of code used possibly pretty often is taken to a separate function.
**Note**: No inlining because it will be called via function pointer in the next step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/134)

rpma: unify client_queue_sync

---

engines/librpma.c
engines/librpma_common.c
engines/librpma_common.h
engines/librpma_gpspm.c

**Note**: This change may affect engines performance because io functions may be linked differently. Especially io_flush function is provided via a function pointer which prevents any compile-time optimizations.
**Note**: This change silently introduces read for GPSPM sync workloads which requires verification.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/131)

rpma: common: client_queue, client_io_write and client_io_read 

---

engines/librpma.c
engines/librpma_common.c
engines/librpma_common.h
engines/librpma_gpspm.c

- get_io_u_index() is getting three possible return values:
- (-1) - on error
- ( 0) - skip
- ( 1) - on success
- client_getevents_process() fix by taking into account
the mentioned above possibility
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/150)

rpma: common: get_io_u_index() skip

---

engines/librpma_common.c

Fix the warning:
```
engines/librpma_common.c: In function ‘librpma_common_client_init’:
engines/librpma_common.c:279:1: warning: label ‘err_free_ccd’ defined but not used [-Wunused-label]
279 | err_free_ccd:
| ^~~~~~~~~~~~
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/167)

rpma: fix warning about unused label ‘err_free_ccd’

---

engines/librpma.c
engines/librpma_gpspm.c

Fix possible null-pointer dereference in client_cleanup().
It can happen when one of unsupported modes is chosen
(for example trim / randtrim / trimwrite ...).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/182)

rpma: fix possible segfault in client_cleanup()

---

engines/librpma_common.c
engines/librpma_common.h
engines/librpma_gpspm.c

**Note**: It may affect the performance of ALL scenarios since this change touches the main processing loops and conditions.
**Note**: It has to be heavily tested to confirm that it fixes the known SQ issue (sporadic).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/181)

rpma: take care of SQ

---

examples/librpma_apm-client.fio
examples/librpma_apm-server.fio

rpma: apm .fio example file with real values for latency measurement
The librpma-apm-*.fio example configurations files should be as complete as possible.
The only ip should be adjusted if needed.
DRAM/malloc is selected for the purpose that the engine could be started without PMem
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/187)

rpma: apm .fio example file with real values for latency measurement

---

engines/librpma_fio.c

Prevent double call of librpma_fio_client_cleanup()
and thus double free of RDMA resources and segfault.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/196)

rpma: prevent double call of librpma_fio_client_cleanup()

---

.github/workflows/ci.yml
configure

The macOS 11.0 ('macos-11.0') virtual environment is currently
provided as a private preview only:
https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/200)

ci: fix MacOS build

---

ci/actions-install.sh

Add the APT::Immediate-Configure APT option.
It fixes the linux i686 schedule build.
See: https://github.com/axboe/fio/pull/1157
See: https://bugs.launchpad.net/ubuntu-cdimage/+bug/1871268
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/201)

ci: add the APT::Immediate-Configure APT option

---

ci/actions-install-librpma.sh

Update LIBRPMA_VERSION to match the version in the upstream PR:
https://github.com/axboe/fio/pull/1186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/205)

ci: update LIBRPMA_VERSION to match the version in the upstream PR

---

engines/librpma_fio.c

It fixes the following memcheck's issue:
==450778== Thread 20:
==450778== Syscall param write(buf) points to uninitialised byte(s)
==450778==    at 0x526FAF7: __libc_write (write.c:26)
==450778==    by 0x526FAF7: write (write.c:24)
==450778==    by 0x5C29D14: rdma_accept (cma.c:1681)
==450778==    by 0x4040F6C: rpma_conn_req_accept (conn_req.c:134)
==450778==    by 0x4041B2E: rpma_conn_req_connect (conn_req.c:421)
==450778==    by 0x4950FE: librpma_fio_server_open_file (librpma_fio.c:978)
==450778==    by 0x4B1C92: server_open_file (librpma_gpspm.c:557)
==450778==    by 0x423D96: td_io_open_file (ioengines.c:502)
==450778==    by 0x44EFD2: get_next_file_rr (io_u.c:1294)
==450778==    by 0x44F23E: __get_next_file (io_u.c:1343)
==450778==    by 0x44F329: get_next_file (io_u.c:1362) …

rpma: zero the librpma_fio_workspace structure

---

ci/actions-install-librpma.sh

Update version of librpma to [78c5dde](https://github.com/pmem/rpma/commit/78c5dde32d6ea38b18485d72f87ff758a320a0a6) with:
- added:
- rpma_cq_get_wc(),
- deprecated:
- rpma_cq_get_completion(),
- struct rpma_completion,
- enum rpma_op
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/264)

ci: update librpma to 78c5dde with rpma_cq_get_wc()
