ci/travis-install-librpma.sh, ci/travis-install.sh, configure
Having the librpma library installed is required by the librpma engine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/4)
=> Install librpma in Travis CI linux build

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/3)
=> rpma: add setup() hook comment

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/8)
=> rpma: split server and client options

engines/librpma.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/7)
=>  rpma: client op scaffolding

examples/librpma-client.fio, examples/librpma-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/5)
=> examples: librpma client and server - sprint 01

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/14)
=> rpma: implement client_post_init()

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/10)
=> rpma: implement client_init()

engines/librpma.c
Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/9)
=> rpma: setup, open_file and close_file hooks impl

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/15)
=> common: reduce the travis matrix

ci/travis-build.sh
|Before [minutes]|After [minutes]|
|---|---|
|~14|~4|
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/16)
=> common: slim down # of tests to reduce regular build time

examples/librpma-client.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/12)
=> examples: add thread & create_serialize

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/23)
=> rpma: make an error message more verbose

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/24)
=> rpma: implement client_queue()

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/22)
=> rpma: fix indentation in client_cleanup()

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/19)
=> rpma: getevents and event implementation

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/21)
=> rpma: errdetails implementation

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/20)
=> rpma: implement client_commit()

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/27)
=> rpma: fix error handling in client_cleanup()

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/25)
=> rpma: align up td->orig_buffer

.travis.yml, ci/travis-build.sh, ci/travis-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/28)
=> common: move the full matrix build to a nightly cron build

engines/librpma.c
Required:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/6)
=> rpma: server op scaffolding

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/30)
=> rpma: set sizes of SQ and CQ

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/33)
=> rpma: replace spaces with tabs

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/29)
=> rpma: consume multiple completions in a single getevents call

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/34)
=> rpma: do sync_io

engines/librpma.c, examples/librpma-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/32)
=> rpma: implement server's side

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/35)
=> rpma: configure librpma logging thresholds in the client

engines/librpma.c, examples/librpma-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/37)
=> rpma: allow server to handle multiple connections

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/39)
=> rpma: add sync write

configure
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/42)
=> rpma: add configure probe for librpma

engines/librpma.c, examples/librpma-client.fio, examples/librpma-server.fio
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/40)
=> rpma: keep threads separately

Makefile, configure, engines/librpma.c, examples/librpma-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/36)
=> rpma: add server_iomem_alloc allocating from PMem

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/41)
=> rpma: allow the server to kill all connections on error

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/45)
=> rpma: set flush_type

engines/librpma.c
We need space for the flush.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/46)
=> rpma: increase SEND_QUEUE in write mode

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/38)
=> rpma: add write mode

Makefile, ci/travis-install.sh, configure
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/49)
=> rpma: add support for linking with libprotobuf-c

engines/librpma.c
Several goto seems to be unnecessary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/44)
=> rpma: remove several goto from server shutdown related routines

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/50)
=> rpma: scaffolding of the GPSPM server

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/52)
=> rpma: scaffolding of the GPSPM client

engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/53)
=> rpma: implement server_init

engines/librpma_gpspm.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/54)
=> implement client_init

engines/librpma_gpspm.c, examples/librpma_gpspm-server.fio
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/55)
=> rpma: implement server_post_init

engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/56)
=> rpma: implement server_cleanup

engines/librpma_gpspm.c, examples/librpma_gpspm-server.fio
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/57)
=> rpma: implement server_open_file and server_close_file

engines/librpma_gpspm.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/58)
=>  rpma: implement client_post_init

engines/librpma_gpspm.c, examples/librpma_gpspm-server.fio
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/59)
=> rpma: implement server_queue

engines/librpma_gpspm.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/61)
=> rpma: implement client_cleanup

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/63)
=> rpma: implement client_get_file_size and client_queue

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/66)
=> rpma: validate both completions in server_queue()

engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/64)
=> rpma: define the last message the client has to send when it is done

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/67)
=> rpma: initiate the next receive operation in server_queue()

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/68)
=> rpma: send the last flush request 'Flush_req_last' in client_cleanup()

engines/librpma_gpspm.c
+ fix allocation size in client_post_innit() hook
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/65)
=> rpma: gpspm client_commit + fix allocation size in client_post_init()

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/70)
=> rpma: remove rpma_conn_completion_wait()

engines/librpma.c, examples/librpma-client.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/43)
=> rpma: mix read/write

engines/librpma.c, examples/librpma-client.fio
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/71)
=>  rpma: pack rpma_flush() into client_io_flush

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/74)
=> rpma: GPSPM server needs real_file_size to initialize io_us

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/78)
=> rpma: gpspm: SQ size (fix)

examples/librpma-client.fio, examples/librpma-server.fio, examples/librpma_gpspm-client.fio, examples/librpma_gpspm-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/75)
=> rpma: cleanup the engines' examples

engines/librpma_gpspm.c
- copy-paste the struct workspace from librpma engine
- copy-paste the workspace validation
- take into account the workspace offset during writing and persisting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/77)
=> rpma: gpspm: improve the thread workspace exchange

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/81)
=> rpma: set the CQ size as needed

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/82)
=> rpma: a single io_u is executed (comment fix)

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/80)
=> rpma: remove redundant td_trimwrite()

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/83)
=> rpma: do not process a cmpl on !IBV_WC_SUCCESS

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/84)
=> rpma: gpspm: limit allowed readwrite values

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/85)
=> rpma: gpspm: do not allow the client-side for waiting in the kernel

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/86)
=> rpma: gpspm: add a "lack of completion is not an error" comment

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/91)
=> rpma: gpspm: rename data -> ws (workspace)

engines/librpma_gpspm.c
XXX probably the message buffer handling is not correct with only this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/87)
=> rpma: gpspm: rework the commit flow to similar as APM has

engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/88)
=> rpma: gpspm: introduce sync mode

engines/librpma.c, engines/librpma_gpspm.c
... instead of an approximation one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/95)
=> rpma: use the exact formula for ceil()

engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/89)
=> rpma: gpspm: rework queue handling

examples/librpma_gpspm-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/92)
=> rpma: gpspm: enrich iodepth description in the server example file

engines/librpma_gpspm.c, examples/librpma_gpspm-client.fio, examples/librpma_gpspm-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/94)
=> rpma: gpspm: a multi-connection (multi-thread) mode

engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/90)
=>  rpma: gpspm: empty the SQ before sending the last message

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/96)
=> rpma: gpspm: set server's queue sizes

engines/librpma_gpspm.c, examples/librpma_gpspm-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/98)
=> rpma: gpspm: check whether io_u buffer is big enough for messages

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/99)
=> rpma: do not process cmpl on RPMA_E_NO_COMPLETION

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/102)
=> rpma: gpspm: fix workspace size

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/100)
=> rpma: gpspm: set correct file size

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/104)
=> rpma: gpspm: add missing error message

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/105)
=> rpma: gpspm: add missing argument of log_err()

engines/librpma_gpspm.c
Having pairs of SEND/RECV buffers, one can not assume an order in which completions from any of them come first to the CQ.
It may happen to collect multiple RECV completions with no SEND completions in the meantime. But since handling RECV requires consuming one SQ slot it is required to control is an SQ slot is available before processing a RECV completion.
The proposed implementation builds up a queue of RECV completions which are processed only when free SQ slots are available.
The number of free SQ slots determines how many RECV completions can be processed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/103)
=> rpma: gpspm: mind the free SQ space

engines/librpma.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/108)
=> rpma: make sure fail is communicated to FIO

engines/librpma.c, examples/librpma-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/110)
=> rpma: do not use memory allocation hooks

Makefile, engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/111)
=> rpma: common: separate common_td_port()

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/113)
=> rpma: common: separate allocate_pmem() and free()

engines/librpma.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/116)
=> rpma: RPMA_LOG_LEVEL_ERROR -> RPMA_LOG_LEVEL_INFO for stdout

engines/librpma_gpspm.c
It is the equivalent of #112 for the GPSPM engine.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/114)
=> rpma: gpspm: each thread registers only its own workspace

engines/librpma.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/117)
=> rpma: start listening ASAP

engines/librpma.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/120)
=> rpma: introduce librpma_common_client_data

engines/librpma.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/123)
=> rpma: common: client_options

engines/librpma.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/127)
=> rpma: common: workspace

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/124)
=>  rpma: common: separate client_init

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/129)
=> rpma: common: file_nop

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/128)
=> rpma: common: get_file_size

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/130)
=> rpma: unify client_io_write() signature

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/133)
=> rpma: common: alloc ccd inside client_init

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/126)
=> rpma: common: post_init

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/125)
=> rpma: common: client_cleanup

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/135)
=> rpma: common: servers' options

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/136)
=> rpma: common: clients' options

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/141)
=> rpma: gpspm: fix post_init

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/137)
=> rpma: common: errdetails

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/138)
=> rpma: common: event

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
**Note**: This change silently introduces read for GPSPM async workloads which requires verification.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/132)
=> rpma: common: client_commit

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/140)
=> rpma: common: server_data, server_init & server_cleanup

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/139)
=> rpma: common: getevents

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/143)
=> rpma: remove unused value

engines/librpma_common.c, engines/librpma_common.h
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/142)
=> rpma: common: servers' open_file and close_file scaffolding

engines/librpma_common.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/144)
=> rpma: use strdup() and handle out of memory

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/145)
=> rpma: gpspm: cleanup order fix

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c, examples/librpma-client.fio, examples/librpma-server.fio, examples/librpma_gpspm-client.fio, examples/librpma_gpspm-server.fio
config file: rename bindname/hostname -> serverip
config structure variable hostname/bindname -> server_ip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/148)
=> rpma: rename bindname/hostname -> serverip

Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/151)
=> rpma: build: use SOURCE instead of ENGINES for common

engines/librpma.c, engines/librpma_common.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/157)
=> rpma: cleanup headers

engines/librpma_common.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/158)
=> rpma: librpma_common_ prefix added to public types

engines/librpma.c, engines/librpma_common.c, engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/147)
=> rpma: return -1 instead of 1 in case of an error

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/149)
=> rpma: use sizeof(variable) instead of sizeof(type)

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/152)
=> rpma: use all 80 characters of the line

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/159)
=> rpma: delete unnecessary lines

engines/librpma_gpspm.c, examples/librpma_gpspm-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/153)
=> rpma: gpspm: do not depend on user-provided blocksize

engines/librpma_common.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/160)
=> rpma: gpspm: max_msg_num (fix)

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/162)
=> rpma: gpspm: fix return value of server_open_file

engines/librpma_common.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/163)
=> rpma: common: client_init() remove conn_cfg_delete

engines/librpma.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/164)
=> rpma: common: client_init() remove conn_cfg_delete (fix)

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
Requires:
- ~~#154~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/155)
=> rpma: direct_write_to_pmem servers' option

engines/librpma_common.c
This code change has been discused already but lost during merge/rebase history
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/161)
=> rpma: all queues deleted in one place

engines/librpma_common.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/166)
=> rpma: --debug=net sets RPMA_LOG_THRESHOLD_AUX to RPMA_LOG_LEVEL_INFO

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/165)
=> rpma: inline assignment with the directly following condition

engines/librpma.c, engines/librpma_common.c, engines/librpma_common.h, engines/librpma_gpspm.c
Requires:
- ~~#154~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/156)
=> rpma: common: server's mr flush type

engines/librpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/168)
=> rpma: apm: build fix

engines/librpma.c, engines/librpma_common.c, engines/librpma_gpspm.c
+ add missing error logs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/169)
=> Unused ret

engines/librpma_common.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/171)
=> rpma: get_ibv_context always call before calloc

examples/librpma-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/172)
=> rpma: numjobs instead of num_jobs

engines/librpma_common.c, engines/librpma_common.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/173)
=> rpma: replace descriptors with descriptor

engines/librpma_common.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/174)
=> rpma: verify if size is aligned to page size

engines/librpma.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/178)
=> rpma: use log_err where log_info mixes with the JSON output

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/175)
=> rpma: gpspm: fix read handling

examples/librpma-client.fio, examples/librpma-server.fio, examples/librpma_gpspm-client.fio, examples/librpma_gpspm-server.fio
- simplify create_serialize requirement
- extend numjobs description
- iomem_align=$pagesize the only valid value
- fix server memory handling description
- fix iodepth GPSPM server description
- unify filename description for both servers
- remove iomem_align from APM server (no longer relevant)
- ...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/176)
=> rpma: fix all examples job files

engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/183)
=> rpma: gpspm: handle free_unpacked on error

Makefile, examples/librpma-client.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/184)
=> rpma: remove redundant spaces at the end of a line

engines/librpma.c, engines/librpma_common.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/185)
=> rpma: fix C-style issues

engines/librpma_common.c, engines/librpma_gpspm.c, examples/librpma-client.fio, examples/librpma_gpspm-client.fio, examples/librpma_gpspm-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/190)
=> rpma: internalize iomem_align

Makefile, engines/librpma_apm.c, engines/librpma_fio.c, engines/librpma_fio.h, engines/librpma_gpspm.c
Proposal to change "common" prefix into "fio"
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/189)
=> rename prefix _commmon_ to _fio_

engines/librpma_apm.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/191)
=> rpma: remove not required engine flags

engines/librpma_apm.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/192)
=> rpma: remove not required engine flags (server)

fio.1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/194)
=> rpma: add RPMA engines option

examples/librpma_apm-client.fio, examples/librpma_apm-server.fio, examples/librpma_gpspm-client.fio, examples/librpma_gpspm-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/195)
=> rpma: .fio example file with real values for latency measurement

engines/librpma_apm.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/197)
=> rpma: print out those logs only in thread #1

ci/actions-install-librpma.sh, engines/librpma_fio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/198)
=> rpma: add RPMA_CONN_REJECTED event handling

engines/librpma_fio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/202)
=> rpma: do not mix two styles of error handling

configure
Check if a version of librpma is new enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/204)
=> rpma: add test for RPMA_CONN_REJECTED

engines/librpma_apm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/207)
=> rpma: return -1 consequently where possible

engines/librpma_apm.c, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/206)
=> rpma: set EINVAL when an unsupported mode is set

engines/librpma_fio.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/208)
=> rpma: remove an obvious comment

ci/actions-install-librpma.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/209)
=> rpma: download archive of librpma using curl

HOWTO
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/210)
=> rpma: add RPMA engines option (HOWTO)

Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/212)
=> rpma: fix Makefile

Makefile, configure, engines/librpma_aof.c, options.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/211)
=> rpma: add AOF scaffolding

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/213)
=> aof: client's data (the zeroth-order approximation)

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/216)
=> aof: client_post_init() (the first approximation)

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/217)
=> aof: client_get_file_size()

engines/librpma_aof.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/215)
=> aof: client_init() (the first approximation)

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/218)
=> aof: client_cleanup() (the first approximation)

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/219)
=> aof: the server's data (the first approximation)

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/223)
=> aof: server: init() and post_init() (the first approximation)

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/222)
=> aof: client_queue_sync() (the first approximation)

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/225)
=> aof: server_close_file()

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/226)
=> aof: server_cleanup (the first approximation)

engines/librpma_aof.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/221)
=> aof: server open_file (the first approximation)

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/227)
=> aof: client: send the last update message

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/228)
=> aof: queue lengths for the async mode

engines/librpma_fio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/231)
=> rpma: gpspm: wait for CQEs of SENDs

engines/librpma_fio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/232)
=> rpma: print info about establishing connection after retries

engines/librpma_fio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/233)
=> [cherry-picked] rpma: gpspm: wait for CQEs of SENDs

engines/librpma_fio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/234)
=> [cherry-picked] rpma: print info about establishing connection after retries

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/230)
=> aof: enable the async mode

engines/librpma_aof.c, engines/librpma_fio.c, engines/librpma_fio.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/229)
=> aof: introduce the 2nd mode (server)

engines/librpma_aof.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/235)
=> aof: introduce the 2nd mode (client)

engines/librpma_fio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/238)
=> rpma: fix printing of connection establishment information after retries

engines/librpma_fio.c
…ation after retries
Ref: #238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/239)
=> [cherry-picked] rpma: fix printing of connection establishment infor

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/240)
=> aof: add client_hw_init()

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/242)
=> aof: add empty server_queue handler

engines/librpma_aof.c
Depends on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/243)
=> aof: add client_hw_get_io_u_index()

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/244)
=> aof: move content of client_sw_post_init() to client_sw_init()

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/245)
=> aof: remove unnecessary option

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/248)
=> aof: fix setting index in client_hw_get_io_u_index()

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/247)
=> aof: add missing EOL in the help messages

engines/librpma_aof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/249)
=> aof: set direct_write_to_pmem

engines/librpma_apm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/250)
=> apm: add missing peer_cfg_delete()

examples/librpma_aof-client.fio, examples/librpma_aof-server.fio
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/246)
=> aof: add librpma_aof_* examples

HOWTO, engines/librpma_fio.c, engines/librpma_fio.h, engines/librpma_gpspm.c, examples/librpma_gpspm-server.fio, fio.1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/251)
=> gpspm: add optional use rpma_conn_completion_wait function

HOWTO, engines/librpma_fio.c, engines/librpma_fio.h, engines/librpma_gpspm.c, examples/librpma_gpspm-server.fio, fio.1
Ref: https://github.com/pmem/fio/pull/251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/253)
=> [cherry-picked] gpspm: add optional use rpma_conn_completion_wait function

engines/librpma_aof.c, engines/librpma_fio.c, engines/librpma_fio.h, examples/librpma_aof-server.fio
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/252)
=> aof: add option to use the rpma_conn_completion_wait() function

engines/librpma_fio.c, engines/librpma_fio.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/256)
=> rpma: adapt to fs-dax mode

ci/actions-install-librpma.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/259)
=> ci: update LIBRPMA_VERSION to support rpma_mr_advise()

engines/librpma_fio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/258)
=> rpma: add rpma_mr_advise calling

engines/librpma_fio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/260)
=> rpma: enhance rpma_mr_advise calling

ci/actions-install-librpma.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/263)
=> ci: update librpma to v0.10.0

engines/librpma_apm.c, engines/librpma_fio.c, engines/librpma_fio.h, engines/librpma_gpspm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/265)
=> rpma: update FIO engines with new completions API

ci/actions-install-librpma.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/266)
=> ci: update librpma to v0.11.0

ci/actions-install-pmdk.sh, ci/actions-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/268)
=> ci: install PMDK 1.11.1

ci/actions-install-pmdk.sh, ci/actions-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/271)
=> ci: set symbolic links for required PMDK libraries

ci/actions-install-pmdk.sh, ci/actions-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/273)
=> ci: run ldconfig instead of creating symlinks manually

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/278)
=> ci: update version of MacOS to match the axboe/master

.github/workflows/ci.yml, ci/actions-clean.sh, ci/actions-install-pmdk.sh, ci/actions-install.sh, ci/verify-rpma.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/284)
=> ci: verify if RPMA engine has been built correctly

.github/workflows/ci.yml, ci/verify-rpma.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/285)
=> ci: verify if required libraries (libpmem or/and libpmem2) are installed

Makefile, configure, engines/librpma_fio.c, engines/librpma_fio.h, engines/librpma_fio_pmem.h, engines/librpma_fio_pmem2.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/fio/269)
=> engines: librpma_fio -  libpmem to libpmem2
